version: '3.8'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    restart: on-failure
    environment:
      - DB_URL=true
    volumes:
      - ./logs:/logs

  database:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=marmaidarmy
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
